otherConfigDB:
  R2212:
    '3':
      edgeconfig:
        3_INSERT_ENV_PROPERTIES_CONFIG.sql:
          VfEdgeNotifyCustomerServices.NotifyCustomerWSConfig.restservice.url: 'https://88.82.4.49/IGW'
    '4':
      edgeconfig:
        4_ARCHIVAL_INSERT_ENV_PROPERTIES_CONFIG.sql:
          comdatalocation: /opt/SP/comdata/wmedgp03
    '16':
      edgeconfig:
        16_INSERT_ENV_PROPERTIES_CONFIG.sql:
          comdatalocation: /opt/SP/comdata/wmedgp03
    '17':
      edgeprocess:
        17_1_INSERT_EDGE_BULK_CONFIGURATION.sql:
          MountPoint: /opt/SP
          EdgeTaskFolderName: wmetaskp21
    '20':
      edgeconfig:
        20_INSERT_ENV_PROP_CONFIG.sql:
          VfTriggerEdgeBulkOrderServices.config.restservice.timeout: 30000
          VfTriggerEdgeBulkOrderServices.config.restservice.connectiontimeout: 30000
          VfTriggerEdgeBulkOrderServices.config.restservice.username: EdgeWMUser
          VfTriggerEdgeBulkOrderServices.config.restservice.password: Pr0dwMU$3r
          VfTriggerEdgeBulkOrderServices.config.restservice.url: >-
            https://wm-edge-b2b-prd.internal.vodafone.co.uk:26254/restv2/EdgeUIManagementServicesV200/UpdateObject
otherConfigDocSync:
  R2212:
    - >-
      Insert into DEPLOYMENT_DOCSYNC
      (RELEASE_NAME,DOC_NAME,STATUS,TARGET_SERVER_ALIAS,FAILED_SERVER_ALIAS,ACTION,UPDATED_TIMESTAMP,ENVIRONMENT,ERROR_MESSAGE)
      values
      ('R2212','VfOrderFulfillmentCanonical.webMethods:OrderFulfillmentCanonical','NEW','b2b_wm2_sw,b2b_wm2_pr,b2b_wm5_sw,b2b_wm5_pr,edge_wm2_sw,edge_wm2_pr,edge_wm3_sw,edge_wm3_pr,edge_wm4_sw,edge_wm4_pr,edge_wm5_sw,edge_wm5_pr,bpms_wm2_sw,bpms_wm2_pr,edgeb2b_wm1_sw,edgeb2b_wm1_pr,edgeb2b_wm2_sw,edgeb2b_wm2_pr,edgeb2b_wm3_sw,edgeb2b_wm3_pr,edgeb2b_wm4_sw,edgeb2b_wm4_pr,edgesupplier_wm1_sw,edgesupplier_wm1_pr,edgenotification_wm3_sw,edgenotification_wm3_pr,bpms_wm3_sw,bpms_wm3_pr,edgeassure_wm1_sw,edgeassure_wm1_pr,edgetask_wm2_sw,edgetask_wm2_pr',null,'DEPLOY',to_timestamp('22-08-22
      10:52:08.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),'prod',null)
    - >-
      Insert into DEPLOYMENT_DOCSYNC
      (RELEASE_NAME,DOC_NAME,STATUS,TARGET_SERVER_ALIAS,FAILED_SERVER_ALIAS,ACTION,UPDATED_TIMESTAMP,ENVIRONMENT,ERROR_MESSAGE)
      values
      ('R2212','VfOrderFulfillmentCanonical.logging:OrderFulfillmentLoggingCanonical','NEW','b2b_wm2_sw,b2b_wm2_pr,b2b_wm5_sw,b2b_wm5_pr,edge_wm2_sw,edge_wm2_pr,edge_wm3_sw,edge_wm3_pr,edge_wm4_sw,edge_wm4_pr,edge_wm5_sw,edge_wm5_pr,bpms_wm2_sw,bpms_wm2_pr,edgeb2b_wm1_sw,edgeb2b_wm1_pr,edgeb2b_wm2_sw,edgeb2b_wm2_pr,edgeb2b_wm3_sw,edgeb2b_wm3_pr,edgeb2b_wm4_sw,edgeb2b_wm4_pr,edgesupplier_wm1_sw,edgesupplier_wm1_pr,edgenotification_wm3_sw,edgenotification_wm3_pr,bpms_wm3_sw,bpms_wm3_pr,edgeassure_wm1_sw,edgeassure_wm1_pr,edgetask_wm2_sw,edgetask_wm2_pr',null,'DEPLOY',to_timestamp('22-08-22
      10:52:08.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),'prod',null)
    - COMMIT
