---
 DeployerServer:
   azagent-nonprod-01:
     host: 10.196.217.115
     port: 6071
     user: EdgeDevopsUser
     pwdhandle: deployer_pwdhandle
   azagent-nonprod-02:
     host: 10.196.217.115
     port: 6071
     user: EdgeDevopsUser
     pwdhandle: deployer_pwdhandle
 edge_wm1:
   edge_wm1:
      host: 10.196.220.54
      port: 6091
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edge_wm2:
   edge_wm2:  
      host: 10.196.220.54
      port: 6092
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edge_wm3:
   edge_wm3:
      host: 10.196.220.54
      port: 6093
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edge_wm4:
   edge_wm4:
      host: 10.196.220.54
      port: 6094
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edge_wm5:
   edge_wm5:
      host: 10.196.220.54
      port: 6096
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 b2b_wm1:
   b2b_wm1:
      host: 10.196.220.54
      port: 6161
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 b2b_wm2:
   b2b_wm2:  
      host: 10.196.220.54
      port: 6162
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 b2b_wm3:
   b2b_wm3:
      host: 10.196.220.54
      port: 6163
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 b2b_wm5:
   b2b_wm5:
      host: 10.196.220.54
      port: 6165
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgesupplier_wm1:
   edgesupplier_wm1:
      host: 10.196.220.54
      port: 6041
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgesupplier_wm2:
   edgesupplier_wm2:
      host: 10.196.220.54
      port: 6042
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgesupplier_wm3:
   edgesupplier_wm3:
      host: 10.196.220.54
      port: 6043
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgeassure_wm1:
   edgeassure_wm1:
      host: 10.196.220.54
      port: 6031
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgeassure_wm2:
   edgeassure_wm2:
      host: 10.196.220.54
      port: 6032
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgeassure_wm3:
   edgeassure_wm3:
      host: 10.196.220.54
      port: 6033
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgeassure_wm4:
   edgeassure_wm4:
      host: 10.196.220.54
      port: 6034
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgeb2b_wm1:
   edgeb2b_wm1:
      host: 10.196.220.54
      port: 6051
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgeb2b_wm2:
   edgeb2b_wm2:
      host: 10.196.220.54
      port: 6052
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgeb2b_wm3:
   edgeb2b_wm3:
      host: 10.196.220.54
      port: 6053
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgeb2b_wm4:
   edgeb2b_wm4:
      host: 10.196.220.54
      port: 6054
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 bpms_wm2:
   bpms_wm2:
      host: 10.196.220.54
      port: 6223
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 bpms_wm3:
   bpms_wm3:
      host: 10.196.220.54
      port: 6224
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgenotification_wm1:
   edgenotification_wm1:
      host: 10.196.220.54
      port: 7071
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgenotification_wm3:
   edgenotification_wm3:
      host: 10.196.220.54
      port: 7073
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgemessaging_wm1:
   edgemessaging_wm1:
      host: 10.196.220.54
      port: 7061
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgemessaging_wm2:
   edgemessaging_wm2:
      host: 10.196.220.54
      port: 7062
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgetask_wm1:
   edgetask_wm1:
      host: 10.196.212.90
      port: 6021
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false
 edgetask_wm2:
   edgetask_wm2:
      host: 10.196.212.90
      port: 6022
      user: EdgeDevopsUser
      pwdhandle: tems2_pwdhandle
      useSSL: false

