otherConfigDB:
  R2306:
    6: 
      edgeconfig:
        6_INSERT_ENV_PROPERTIES_CONFIG.sql:
          Server_path_1: /opt/SP/comdata/wmedgtsk14/SupplierFootprintData/AccessNetInventory/outbound/processing/
          Server_path_2: /opt/SP/comdata/wmedgtsk14/SupplierFootprintData/EdgeProductCoverageConfig/outbound/processing/
          Server_path_3: /opt/SP/comdata/wmedgtsk14/SupplierFootprintData/EdgeProductPromotion/outbound/processing/
          Server_path_4: /opt/SP/comdata/wmedgtsk14/SupplierFootprintData/AccessNetInventory/outbound/processed/
          Server_path_5: /opt/SP/comdata/wmedgtsk14/SupplierFootprintData/EdgeProductCoverageConfig/outbound/processed/
          Server_path_6: /opt/SP/comdata/wmedgtsk14/SupplierFootprintData/EdgeProductPromotion/outbound/processed/
          Server_path_7: /opt/SP/comdata/wmedgtsk14/SupplierFootprintData/AccessNetInventory/outbound/archive/
          Server_path_8: /opt/SP/comdata/wmedgtsk14/SupplierFootprintData/EdgeProductCoverageConfig/outbound/archive/
          Server_path_9: /opt/SP/comdata/wmedgtsk14/SupplierFootprintData/EdgeProductPromotion/outbound/archive/
